### ISSUE TITLE
Adding OMSCSNotes to your README

### ISSUE THREAD

**Issue by m4ttsch** [katgironpe/awesome-omscs#4]
Hey there!

I own and develop a site called [OMSCSNotes](https://www.omscs-notes.com/) where I share all of my lecture notes for the classes I have taken in OMSCS. So far, I have content for GIOS, IIS, CN, ML4T, and Simulation. By the end of the program, I will likely add ML, RL, GA, AI, and one other.

Since I built the site in mid-2019, I've had 27,000 users visit the site and just shy of 250,000 page views. People tell me they love it, and I think it's a great resource. Can we add it to your README for more visibility?

Thanks,
Matt Schlenker

**Comment by kathgironpe** [comment]
Hello sure will add

**Comment by m4ttsch** [comment]
Hey thanks!

**Comment by kathgironpe** [comment]
It was already there for some time BTW.

**Comment by kathgironpe** [comment]
@m4ttsch It was there since 2019. Thanks for your notes. Adding you as collaborator if you have anything more to add here.
